if (DEFINED ENV{CODE})
    message(STATUS "External libraries prebuilt in $CODE=" $ENV{CODE})
    if(EXISTS $ENV{CODE}/libneo/build/)
        set(LIBNEO_DIR $ENV{CODE}/libneo/build/ CACHE STRING "libneo directory")
    endif()
    if(EXISTS $ENV{CODE}/external/fgsl-1.6.0/)
        set(FGSL_DIR $ENV{CODE}/external/fgsl-1.6.0/ CACHE STRING "FGSL directory")
    endif()
    if(EXISTS $ENV{CODE}/external/triangle/)
        set(TRIANGLE_DIR $ENV{CODE}/external/triangle/ CACHE STRING "TRIANGLE directory")
    endif()
    if(EXISTS $ENV{CODE}/external/mfem-4.7/build/)
        set(MFEM_DIR $ENV{CODE}/external/mfem-4.7/build/ CACHE STRING "MFEM directory")
    endif()
else()
    message(STATUS "Downloading and building external libraries")
endif()
